# Get the update manifest
def update_manifest
  document = Builder::XmlMarkup.new(:indent => 2)
  
  document.updates do |updates|
    updates.comment! "Update manifest: Generated by Builder Script at #{Time.now}"
    updates.update do |u|
      u.name $package['package']['name']
      u.description $package['package']['description']
      u.type 'package'
      u.version version_name
      u.infourl "http://www.mrzen.com/travelzen"
      u.client 'site'
      u.downloads do |d|
        d.downloadurl({:type => "full" , :format => "zip"}, "#{$package['package']['update_site']}/#{package_name}.zip")
      end
    end
  end

  document.target!
end
